import "./aboutus.css";
import "./appoiments.css";
import "./banner.css";
import "./contact-detail.css";
import "./department.css";
import "./expert.css";
import "./footer.css";
import "./form.css";
// import "./header.css";
import "./main.css";
// import "./navbar.css";
import "./news.css";
import "./notFound.css";
import "./qestion.css";
import "./testimonial.css";
import "./workinghour.css";
import "./appoimentsPage.css";
import "./faq.css";
import "./pagination.css";
import "./teams.css";
import "./albums.css";
import "./blogDetails.css";
import "./SerivesDetails.css";
import "./customSlilck.css";
import "./aboutus_detail.css";
import "./responsive.css";
